---

- hosts: all
  vars:
    girder_update: no
    girder_force: no
    girder_virtualenv: "{{ ansible_user_dir }}/.virtualenvs/girder"
    girder_always_build_assets: yes
    girder_web_extra_args: "--dev"
  pre_tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      become: yes
      become_user: root
      when: ansible_os_family == "Debian"

    - name: Install EPEL
      yum:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
        state: present
      become: yes
      become_user: root
      when: ansible_os_family == "RedHat"

  roles:
    - role: Stouts.mongodb
      become: yes
      become_user: root
      when: ansible_os_family == "Debian"
    - role: redhat-mongodb
      become: yes
      become_user: root
      when: ansible_os_family == "RedHat"
    - role: girder

  post_tasks:
    - name: Install Girder Python development requirements
      pip:
        requirements: "requirements-dev.txt"
        chdir: "{{ girder_path }}"
        virtualenv: "{{ girder_virtualenv }}"

    - name: Install development packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - cmake
        - cmake-curses-gui
      become: yes
      become_user: root
      when: ansible_os_family == "Debian"

    - name: Install development packages
      yum:
        name: "cmake"
        state: present
      become: yes
      become_user: root
      when: ansible_os_family == "RedHat"

    - name: Activate virtualenv on login
      lineinfile:
        dest: "{{ ansible_user_dir }}/.profile"
        line: 'source {{ girder_virtualenv }}/bin/activate'
        state: present
