language: python
python:
    - "2.7"
    - "3.4"

sudo: false

env:
    - MONGO_VERSION=2.6.9 DEPLOY=true
    - MONGO_VERSION=3.0.2

compiler:
    - gcc
before_install:
    # Show the memory state; this lets us more quickly determine when the
    # travis environment is bad
    - vmstat
    - echo ${TRAVIS_PYTHON_VERSION}

    - pushd "${HOME}"
    - curl "https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGO_VERSION}.tgz" | gunzip -c | tar x
    - cd mongodb-*/bin && export PATH="${PWD}:${PATH}"
    - popd
    - mkdir /tmp/db
    - mongod --dbpath=/tmp/db >/dev/null 2>/dev/null &

    - mongod --version
    - pushd "${HOME}"
    - curl "http://www.cmake.org/files/v3.1/cmake-3.1.0-Linux-x86_64.tar.gz" | gunzip -c | tar x
    - cd cmake-*/bin && export PATH="${PWD}:${PATH}"
    - popd
    - cmake --version
install:
    - mkdir -p "${HOME}/.local/bin"
    - export PATH="${HOME}/.local/bin:${PATH}"
    - pip install -r requirements.txt -r requirements-dev.txt -r plugins/geospatial/requirements.txt -r plugins/metadata_extractor/requirements.txt
    - pip install -r plugins/celery_jobs/requirements.txt -r plugins/hdfs_assetstore/requirements.txt
    # We have to upgrade six or requiring moto can cause other modules to fail
    - pip install -U six
    - npm install grunt grunt-cli
    - npm install
script:
    - mkdir _build
    - cd _build
    - cmake ..
    - JASMINE_TIMEOUT=15000 ctest -VV -S ../cmake/travis_continuous.cmake || true
    - if [ -f test_failed ] ; then false ; fi
    - cd ..
    - git fetch --unshallow
deploy:
    provider: heroku
    buildpack: https://github.com/ddollar/heroku-buildpack-multi.git
    strategy: git
    api_key:
        secure: RflKHQjdjo4dpebNUGHJrAi4cOchQPtKiA5q9W0iXJ09T2Ad/gZhJqwPN/MKzPb2JTRZzxrVBergjAeTjxcaVbNh97JnC+NBa77A5VFhCDELB2sN/zwjmxpiTtTgDtD8N2MOQcLoc7T8x0TRhk2pANQB3ztrvy+oDX+mq5SbuuU=
    app: girder-test
    on:
        repo: girder/girder
        branch: master
        condition: "$DEPLOY = true"
