language: python
python:
    - 2.7
    - 3.4

env:
    - GIRDER_TEST_GROUP=python
    - GIRDER_TEST_GROUP=browser

matrix:
    exclude:
        - python: 3.4
          env: GIRDER_TEST_GROUP=browser

cache:
    directories:
        - $HOME/.cache

sudo: false

compiler:
    - gcc
before_install:
    # Show the memory state; this lets us more quickly determine when the
    # travis environment is bad
    - vmstat
    - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "3" ]; then export PY3="true"; else export PY2="true"; fi
    - if [ -n "${PY3}" ]; then export MONGO_VERSION=3.0.7; export PY_COVG="OFF"; else export MONGO_VERSION=2.6.11; export PY_COVG="ON"; export DEPLOY=true; fi
    - if [ -n "${PY3}" ]; then export IGNORE_PLUGINS=hdfs_assetstore,metadata_extractor; fi
    - CACHE=$HOME/.cache source ./scripts/install_mongo.sh
    - mkdir /tmp/db
    - (mongod --dbpath=/tmp/db >/dev/null 2>/dev/null || true ) &
    - mongod --version || true
    - CACHE=$HOME/.cache CMAKE_VERSION=3.4.3 CMAKE_SHORT_VERSION=3.4 source ./scripts/install_cmake.sh
    - cmake --version
    - mkdir -p $HOME/.cache/node_modules || true
    - ln -sf $HOME/.cache/node_modules .
    - nvm install v5
    - npm install -g npm
    - node --version
    - npm --version
    - npm prune
    - pip install -U pip virtualenv
install:
    - pip install -r requirements-dev.txt -e .[plugins] -e clients/python
    - npm install
    - npm run build
script:
    - mkdir _build
    - cd _build
    - cmake -DPYTHON_COVERAGE:BOOL=${PY_COVG} -DPYTHON_VERSION:STRING=${TRAVIS_PYTHON_VERSION} ..
    - JASMINE_TIMEOUT=15000 ctest -VV -S ../cmake/travis_continuous.cmake || true
    - if [ -f test_failed ] ; then false ; fi
    - cd ..
    - git fetch --unshallow
deploy:
    provider: heroku
    buildpack: https://github.com/ddollar/heroku-buildpack-multi.git
    strategy: git
    api_key:
        secure: RflKHQjdjo4dpebNUGHJrAi4cOchQPtKiA5q9W0iXJ09T2Ad/gZhJqwPN/MKzPb2JTRZzxrVBergjAeTjxcaVbNh97JnC+NBa77A5VFhCDELB2sN/zwjmxpiTtTgDtD8N2MOQcLoc7T8x0TRhk2pANQB3ztrvy+oDX+mq5SbuuU=
    app: girder-test
    on:
        repo: girder/girder
        branch: master
        condition: "$DEPLOY = true"
