---
girder_bind_public: false
girder_daemonize: true
girder_database_uri: "mongodb://localhost:27017/girder"
girder_development_mode: false
girder_version: "latest"
girder_virtualenv: "{{ ansible_user_dir }}/.virtualenvs/girder"
girder_web: true
