---

- block:
    - name: Install Girder system dependencies
      apt:
        name: "{{ item }}"
      with_items:
        - gcc
        - git
        # Needed for 'ldap' plugin
        - libldap2-dev
        - libsasl2-dev

    # Python dev headers are only installed if the user hasn't specified a python executable
    - name: Install Python development headers
      apt:
        name: python2.7-dev
      when: girder_python is not defined

    # Pip is only installed via the package manager if an existing pip wasn't defined
    # *and* a custom python wasn't defined. If a custom Python is defined the user
    # is expected to have installed their own development headers and pip.
    - name: Install pip
      apt:
        name: python-pip
      when: girder_python is not defined and girder_pip is not defined
  become: yes
  become_user: root
  when: ansible_os_family == "Debian"

- block:
    - name: Install Girder system dependencies
      yum:
        name: "{{ item }}"
      with_items:
        - gcc
        - git
        # Needed for 'ldap' plugin
        - openldap-devel

    - name: Install Python development headers
      yum:
        name: python-devel
      when: girder_python is not defined

    - name: Install pip
      yum:
        name: python2-pip
      when: girder_python is not defined and girder_pip is not defined

  become: yes
  become_user: root
  when: ansible_os_family == "RedHat"

- name: Download Girder
  git:
    repo: "{{ girder_repo }}"
    dest: "{{ girder_path }}"
    version: "{{ girder_version }}"
    update: "{{ girder_update|default(omit) }}"
    force: "{{ girder_force|default(omit) }}"
    clone: "{{ girder_clone|default(omit) }}"
  register: vc

- set_fact:
    girder_files_updated: "{{ vc.changed }}"

- name: Get Girder's major version
  shell: sed -n "s/__version__ = '\([^.]*\).*'.*/\1/p" < "{{ girder_path }}/girder/__init__.py"
  register: girder_major_version
