---

- name: Build Girder web client
  environment:
    - LC_ALL: "C.UTF-8"
    - LANG: "C.UTF-8"
  command: "{{ girder_virtualenv }}/bin/girder build --static-public-path /static"
  when: girder_web

- name: Restart Girder
  systemd:
    name: girder
    daemon_reload: true
    state: restarted
  become: true
  become_user: root
  when: girder_daemonize
