galaxy_info:
  author: Kitware, Inc.
  description: Install the Girder data management platform.
  company: Kitware, Inc.

  license: Apache
  min_ansible_version: 1.9

  platforms:
  - name: Ubuntu
    versions:
    - trusty

  galaxy_tags:
    - girder

dependencies:
  - role: nodesource.node
    nodejs_version: "4.4"
    become: yes
    become_user: root
  - role: Stouts.mongodb
    mongodb_version: "3.2"
    mongodb_conf_cpu: no
    mongodb_conf_dbpath: "/var/lib/mongodb"
    mongodb_conf_journal: yes
    become: yes
    become_user: root
