---
- name: Prepare
  hosts: targets
  tasks:
    # gpg is needed to add other APT repositories
    - name: Install gnupg2
      apt:
        update_cache: true
        name: gnupg2
        state: present
        force_apt_get: true
      become: true
      become_user: root
