---

- hosts: all
  vars:
    girder_update: no
    girder_force: no
    girder_always_build_assets: yes
    girder_web_extra_args: "--all-plugins"
    girder_hardened: yes
    nginx_vhosts:
      - listen: "8080 default_server"
        ssl_certificate_key: "/etc/ssl/default_server/default_server.key"
        ssl_certificate: "/etc/ssl/default_server/default_server.pem"
        server_name: "girder-hardened"
        extra_parameters: |
          ssl on;
          ssl_certificate_key /etc/ssl/default_server/default_server.key;
          ssl_certificate /etc/ssl/default_server/default_server.pem;

          add_header X-Content-Type-Options nosniff;
          add_header X-Frame-Options DENY;
          add_header Content-Security-Policy "style-src 'self'
                                                        'sha256-I08hTk63KqFj9IjGtMeORROxIYJYsBEazDOd2hkXWZY='
                                                        'sha256-zB4+dg/iQaGd+pLwCZo03/lJhn/b6UNYzJppzv3EEAc='
                                                        'sha256-h8Ck0CS7cKiFtPMm/8DjdkPXgP8gxqL7G997urcLS28='
                                                        'sha256-MGNMaa1KDEaQ0N9k9XVIdXWtkb9PIkCbTCFGKcQTs7Q=';
                                              font-src 'self';
                                              script-src 'self'
                                                         'sha256-MKRiXCHIn6830x4q3pvDhTPRHXpThPnEVF6dkhVBqm8='";

          location / {
            proxy_set_header Host $proxy_host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://localhost:8888/;
            # Must set the following for SSE notifications to work
            proxy_buffering off;
            proxy_cache off;
            proxy_set_header Connection '';
            proxy_http_version 1.1;
            chunked_transfer_encoding off;
            proxy_read_timeout 600s;
            proxy_send_timeout 600s;
          }

  pre_tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      become: yes
      become_user: root

  roles:
    - role: Stouts.mongodb
      become: yes
      become_user: root
    - role: girder
    - role: jdauphant.ssl-certs
      ssl_certs_common_name: "default_server"
      become: yes
      become_user: root
    - role: geerlingguy.nginx
      become: yes
      become_user: root

  post_tasks:
    - name: Tweak Girder server configurations
      ini_file:
        dest: "{{ girder_path }}/girder/conf/girder.local.cfg"
        backup: yes
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
        - { section: "global", option: "server.thread_pool", value: "1000" }
        - { section: "global", option: "server.socket_port", value: "8888" }
        - { section: "global", option: "tools.proxy.on", value: "True" }
        - { section: "server", option: "mode", value: '"production"' }

    - name: restart girder/nginx
      service:
        state: restarted
        name: "{{ item }}"
      with_items:
        - girder
        - nginx
      become: yes
      become_user: root
